version: "3.7"

services:
  postgres:
    image: "postgres:12-alpine"
    restart: always
    environment:
      POSTGRES_USER: study_manager
      POSTGRES_PASSWORD: letmein
    ports:
      - "54321:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: phoenix_base
    command: mix phx.server
    ports:
      - "4000:4000"
    volumes:
      - ./:/app:cached
      - deps_cache:/opt/mix/deps
      - compile_cache:/opt/mix/build
    depends_on:
      - postgres

  test:
    build:
      context: .
      target: phoenix_base
    command: mix test.watch
    environment:
      MIX_ENV: test
    volumes:
      - ./:/app:cached
      - deps_cache:/opt/mix/deps
      - compile_cache:/opt/mix/build
    depends_on:
      - postgres

volumes:
  pg_data:
  deps_cache:
  compile_cache:

networks:
  default:
    name: study_manager.local
