name: E2E Tests

on: push

jobs:
  e2e:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cypress run
      uses: cypress-io/github-action@v1
      with:
        build: >
          docker-compose run --rm app sh -c "mix ecto.setup &&
                                             cd assets &&
                                             npm install"
        start: docker-compose up app
        wait-on: 'http://localhost:4000/'
        wait-on-timeout: 120
